source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'apotomo', '1.1.1'
gem 'haml'
gem 'inherited_resources'
gem "ordered_tree", "0.1.1" # have to include ordered tree here because I haven't found a way to include what gems navi relies on; since we just edited the config/boot.rb to add navi's lib to the loadpath.
gem 'jquery-rails', '>= 1.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'rspec-rails', '2.6.1'
  gem 'cucumber-rails', '0.4.1'
  gem 'capybara', '0.4.1.2'
  gem 'guard-cucumber', '0.3.4'
  gem 'libnotify'
  gem 'rb-inotify'
  gem 'nifty-generators'
end
